FROM openjdk:17-ea-3-jdk-slim-buster
COPY ./target/notification-service-0.0.1-SNAPSHOT.jar /notification-service-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar" , "/notification-service-0.0.1-SNAPSHOT.jar"]


