server:
  port: 8089

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-service
#      uri: mongodb+srv://hassona:hassona1234@cluster1.5we3q3v.mongodb.net/ac-bxgd6tk-shard-00-01
#      database: ac-bxgd6tk-shard-00-01

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/


spring.kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

springdoc:
  swagger-ui:
    path: /docs