FROM openjdk:17-ea-3-jdk-slim-buster
COPY ./target/shopping-cart-service-0.0.1-SNAPSHOT.jar /shopping-cart-service-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar" , "/shopping-cart-service-0.0.1-SNAPSHOT.jar"]


