
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/

logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE
                    gateway.route.RouteDefinitionRouteLocator: INFO
        root: INFO
server:
    port: 8000
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowed-headers: "*"
                        allowed-methods: "*"
                        allowed-origins: "*"
            routes:
            - id: payment-service
              uri: http://localhost:8084
              predicates:
                  - Path=/payment/**
            - id: product-service
              uri: http://localhost:8082
              predicates:
                  - Path=/products/**
            - id: order-service
              uri: http://localhost:8083
              predicates:
                  - Path=/api/order/**
            - id: notification-service
              uri: http://localhost:8085
              predicates:
                  - Path=/api/notification
            - id: discovery-server
              uri: http://localhost:8761
              predicates:
                  - Path=/eureka/web
            - id: shopping-cart-service
              uri: http://localhost:8088
              predicates:
                  - Path=/api/shopping
            - id: user-service
              uri: http://localhost:8089
              predicates:
                  - Path=/api/users/**
            - id: discovery-server-static
              uri: http://localhost:8761
              predicates:
                  - Path=/eureka/**
            - id: openapi
              uri: http://localhost:${server.port}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/prototype-realm


springdoc:
  swagger-ui:
    urls:
      - name: order
        url: /v3/api-docs/order
